title: "BAM Tutorials"
description: "Boreal Avian Modelling Project"

#baseurl:  http://localhost:4000
baseurl: https://borealbirds.github.io/tutorials

include: [".htaccess"]
exclude: ["README.md","LICENSE"]
timezone: America/Edmonton

permalink: /:categories/:title:output_ext

# topic name is the jekyll category
topics:
  - name: setup
    title: 'Setting up the workflow'
    description:
  - name: bamdb
    title: 'Processing avian data'
    description:
  - name: gis
    title: 'Processing geospatial data'
    description:
  - name: qpad
    title: 'Estimating and calculating offsets'
    description:
  - name: models
    title: 'Modeling species'
    description:

encoding: UTF-8
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
markdown_ext: "markdown,mkdown,mkdn,mkd,md,rmd,Rmd"

# Bootswatch theme
bswtheme: cosmo
# fancy fonts on/off
fancyfonts: true
# navbar style: inverse, transparent
navbar: transparent

# disqus id comes here
disqus:

author: "<a href='http://borealbirds.ca'>Boreal Avian Modelling Project</a>"
author_plain: 'Boreal Avian Modelling Project'

gems:
  - jekyll-feed
  - jekyll-sitemap
