title: "BAM Tutorials"
description: "Boreal Avian Modelling Project"

#baseurl:  http://localhost:4000
baseurl: https://borealbirds.github.io/tutorials

include: [".htaccess"]
exclude: ["README.md","LICENSE"]
timezone: America/Edmonton

categories: ["setup", "data", "qpad", "models"]
permalink: /:categories/:title:output_ext

encoding: UTF-8
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
markdown_ext: "markdown,mkdown,mkdn,mkd,md,rmd,Rmd"

# Bootswatch theme (cosmo)
bswtheme: yeti
# fancy fonts on/off
fancyfonts: true
# navbar style: inverse, transparent
navbar: transparent

# disqus id comes here
disqus:
# show google ads?
ads: false

author: "<a href='http://borealbirds.ca'>Boreal Avian Modelling Project</a>"
author_plain: 'Boreal Avian Modelling Project'

gems:
  - jekyll-feed
  - jekyll-sitemap
